/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ShopkeeperRouteImport } from './routes/shopkeeper'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CustomerRouteImport } from './routes/customer'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as ShopkeeperSettingsRouteImport } from './routes/shopkeeper.settings'
import { Route as ShopkeeperReviewsRouteImport } from './routes/shopkeeper.reviews'
import { Route as ShopkeeperProductsRouteImport } from './routes/shopkeeper.products'
import { Route as ShopkeeperOrdersRouteImport } from './routes/shopkeeper.orders'
import { Route as ShopkeeperOffersRouteImport } from './routes/shopkeeper.offers'
import { Route as ShopkeeperNotificationsRouteImport } from './routes/shopkeeper.notifications'
import { Route as ShopkeeperEarningsRouteImport } from './routes/shopkeeper.earnings'
import { Route as ShopkeeperDashboardRouteImport } from './routes/shopkeeper.dashboard'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as DeliveryProfileRouteImport } from './routes/delivery.profile'
import { Route as DeliveryNotificationsRouteImport } from './routes/delivery.notifications'
import { Route as DeliveryHistoryRouteImport } from './routes/delivery.history'
import { Route as DeliveryEarningsRouteImport } from './routes/delivery.earnings'
import { Route as DeliveryDashboardRouteImport } from './routes/delivery.dashboard'
import { Route as DeliveryAvailableOrdersRouteImport } from './routes/delivery.available-orders'
import { Route as CustomerWishlistRouteImport } from './routes/customer.wishlist'
import { Route as CustomerShopRouteImport } from './routes/customer.shop'
import { Route as CustomerProfileRouteImport } from './routes/customer.profile'
import { Route as CustomerOrdersRouteImport } from './routes/customer.orders'
import { Route as CustomerNotificationsRouteImport } from './routes/customer.notifications'
import { Route as CustomerHomeRouteImport } from './routes/customer.home'
import { Route as CustomerCheckoutRouteImport } from './routes/customer.checkout'
import { Route as CustomerCategoriesRouteImport } from './routes/customer.categories'
import { Route as CustomerCartRouteImport } from './routes/customer.cart'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as AdminShopsRouteImport } from './routes/admin.shops'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminOffersRouteImport } from './routes/admin.offers'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminDeliveryPartnersRouteImport } from './routes/admin.delivery-partners'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminComplaintsRouteImport } from './routes/admin.complaints'
import { Route as AdminCollectionsRouteImport } from './routes/admin.collections'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as ShopkeeperOrdersIdRouteImport } from './routes/shopkeeper.orders.$id'
import { Route as DeliveryTaskIdRouteImport } from './routes/delivery.task.$id'
import { Route as CustomerProductIdRouteImport } from './routes/customer.product.$id'
import { Route as CustomerOrdersIdRouteImport } from './routes/customer.orders.$id'
import { Route as ApiPublicOneSignalSDKWorkerDotjsRouteImport } from './routes/api/public/OneSignalSDKWorker[.]js'
import { Route as ApiPublicOneSignalSDKUpdaterWorkerDotjsRouteImport } from './routes/api/public/OneSignalSDKUpdaterWorker[.]js'
import { Route as AdminOrdersIdRouteImport } from './routes/admin.orders.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopkeeperRoute = ShopkeeperRouteImport.update({
  id: '/shopkeeper',
  path: '/shopkeeper',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRoute = CustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopkeeperSettingsRoute = ShopkeeperSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShopkeeperRoute,
} as any)
const ShopkeeperReviewsRoute = ShopkeeperReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => ShopkeeperRoute,
} as any)
const ShopkeeperProductsRoute = ShopkeeperProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => ShopkeeperRoute,
} as any)
const ShopkeeperOrdersRoute = ShopkeeperOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => ShopkeeperRoute,
} as any)
const ShopkeeperOffersRoute = ShopkeeperOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => ShopkeeperRoute,
} as any)
const ShopkeeperNotificationsRoute = ShopkeeperNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ShopkeeperRoute,
} as any)
const ShopkeeperEarningsRoute = ShopkeeperEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => ShopkeeperRoute,
} as any)
const ShopkeeperDashboardRoute = ShopkeeperDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ShopkeeperRoute,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryProfileRoute = DeliveryProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DeliveryRoute,
} as any)
const DeliveryNotificationsRoute = DeliveryNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DeliveryRoute,
} as any)
const DeliveryHistoryRoute = DeliveryHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DeliveryRoute,
} as any)
const DeliveryEarningsRoute = DeliveryEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => DeliveryRoute,
} as any)
const DeliveryDashboardRoute = DeliveryDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DeliveryRoute,
} as any)
const DeliveryAvailableOrdersRoute = DeliveryAvailableOrdersRouteImport.update({
  id: '/available-orders',
  path: '/available-orders',
  getParentRoute: () => DeliveryRoute,
} as any)
const CustomerWishlistRoute = CustomerWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerShopRoute = CustomerShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerProfileRoute = CustomerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerOrdersRoute = CustomerOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerNotificationsRoute = CustomerNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerHomeRoute = CustomerHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerCheckoutRoute = CustomerCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerCategoriesRoute = CustomerCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerCartRoute = CustomerCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => CustomerRoute,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShopsRoute = AdminShopsRouteImport.update({
  id: '/shops',
  path: '/shops',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOffersRoute = AdminOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDeliveryPartnersRoute = AdminDeliveryPartnersRouteImport.update({
  id: '/delivery-partners',
  path: '/delivery-partners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminComplaintsRoute = AdminComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCollectionsRoute = AdminCollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const ShopkeeperOrdersIdRoute = ShopkeeperOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ShopkeeperOrdersRoute,
} as any)
const DeliveryTaskIdRoute = DeliveryTaskIdRouteImport.update({
  id: '/task/$id',
  path: '/task/$id',
  getParentRoute: () => DeliveryRoute,
} as any)
const CustomerProductIdRoute = CustomerProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerOrdersIdRoute = CustomerOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CustomerOrdersRoute,
} as any)
const ApiPublicOneSignalSDKWorkerDotjsRoute =
  ApiPublicOneSignalSDKWorkerDotjsRouteImport.update({
    id: '/api/public/OneSignalSDKWorker.js',
    path: '/api/public/OneSignalSDKWorker.js',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicOneSignalSDKUpdaterWorkerDotjsRoute =
  ApiPublicOneSignalSDKUpdaterWorkerDotjsRouteImport.update({
    id: '/api/public/OneSignalSDKUpdaterWorker.js',
    path: '/api/public/OneSignalSDKUpdaterWorker.js',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminOrdersIdRoute = AdminOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminOrdersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/customer': typeof CustomerRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/delivery': typeof DeliveryRouteWithChildren
  '/login': typeof LoginRoute
  '/products': typeof ProductsRoute
  '/shopkeeper': typeof ShopkeeperRouteWithChildren
  '/signup': typeof SignupRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/collections': typeof AdminCollectionsRoute
  '/admin/complaints': typeof AdminComplaintsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/delivery-partners': typeof AdminDeliveryPartnersRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shops': typeof AdminShopsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/customer/cart': typeof CustomerCartRoute
  '/customer/categories': typeof CustomerCategoriesRoute
  '/customer/checkout': typeof CustomerCheckoutRoute
  '/customer/home': typeof CustomerHomeRoute
  '/customer/notifications': typeof CustomerNotificationsRoute
  '/customer/orders': typeof CustomerOrdersRouteWithChildren
  '/customer/profile': typeof CustomerProfileRoute
  '/customer/shop': typeof CustomerShopRoute
  '/customer/wishlist': typeof CustomerWishlistRoute
  '/delivery/available-orders': typeof DeliveryAvailableOrdersRoute
  '/delivery/dashboard': typeof DeliveryDashboardRoute
  '/delivery/earnings': typeof DeliveryEarningsRoute
  '/delivery/history': typeof DeliveryHistoryRoute
  '/delivery/notifications': typeof DeliveryNotificationsRoute
  '/delivery/profile': typeof DeliveryProfileRoute
  '/orders/$id': typeof OrdersIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/shopkeeper/dashboard': typeof ShopkeeperDashboardRoute
  '/shopkeeper/earnings': typeof ShopkeeperEarningsRoute
  '/shopkeeper/notifications': typeof ShopkeeperNotificationsRoute
  '/shopkeeper/offers': typeof ShopkeeperOffersRoute
  '/shopkeeper/orders': typeof ShopkeeperOrdersRouteWithChildren
  '/shopkeeper/products': typeof ShopkeeperProductsRoute
  '/shopkeeper/reviews': typeof ShopkeeperReviewsRoute
  '/shopkeeper/settings': typeof ShopkeeperSettingsRoute
  '/orders/': typeof OrdersIndexRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/api/public/OneSignalSDKUpdaterWorker.js': typeof ApiPublicOneSignalSDKUpdaterWorkerDotjsRoute
  '/api/public/OneSignalSDKWorker.js': typeof ApiPublicOneSignalSDKWorkerDotjsRoute
  '/customer/orders/$id': typeof CustomerOrdersIdRoute
  '/customer/product/$id': typeof CustomerProductIdRoute
  '/delivery/task/$id': typeof DeliveryTaskIdRoute
  '/shopkeeper/orders/$id': typeof ShopkeeperOrdersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/customer': typeof CustomerRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/delivery': typeof DeliveryRouteWithChildren
  '/login': typeof LoginRoute
  '/products': typeof ProductsRoute
  '/shopkeeper': typeof ShopkeeperRouteWithChildren
  '/signup': typeof SignupRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/collections': typeof AdminCollectionsRoute
  '/admin/complaints': typeof AdminComplaintsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/delivery-partners': typeof AdminDeliveryPartnersRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shops': typeof AdminShopsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/customer/cart': typeof CustomerCartRoute
  '/customer/categories': typeof CustomerCategoriesRoute
  '/customer/checkout': typeof CustomerCheckoutRoute
  '/customer/home': typeof CustomerHomeRoute
  '/customer/notifications': typeof CustomerNotificationsRoute
  '/customer/orders': typeof CustomerOrdersRouteWithChildren
  '/customer/profile': typeof CustomerProfileRoute
  '/customer/shop': typeof CustomerShopRoute
  '/customer/wishlist': typeof CustomerWishlistRoute
  '/delivery/available-orders': typeof DeliveryAvailableOrdersRoute
  '/delivery/dashboard': typeof DeliveryDashboardRoute
  '/delivery/earnings': typeof DeliveryEarningsRoute
  '/delivery/history': typeof DeliveryHistoryRoute
  '/delivery/notifications': typeof DeliveryNotificationsRoute
  '/delivery/profile': typeof DeliveryProfileRoute
  '/orders/$id': typeof OrdersIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/shopkeeper/dashboard': typeof ShopkeeperDashboardRoute
  '/shopkeeper/earnings': typeof ShopkeeperEarningsRoute
  '/shopkeeper/notifications': typeof ShopkeeperNotificationsRoute
  '/shopkeeper/offers': typeof ShopkeeperOffersRoute
  '/shopkeeper/orders': typeof ShopkeeperOrdersRouteWithChildren
  '/shopkeeper/products': typeof ShopkeeperProductsRoute
  '/shopkeeper/reviews': typeof ShopkeeperReviewsRoute
  '/shopkeeper/settings': typeof ShopkeeperSettingsRoute
  '/orders': typeof OrdersIndexRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/api/public/OneSignalSDKUpdaterWorker.js': typeof ApiPublicOneSignalSDKUpdaterWorkerDotjsRoute
  '/api/public/OneSignalSDKWorker.js': typeof ApiPublicOneSignalSDKWorkerDotjsRoute
  '/customer/orders/$id': typeof CustomerOrdersIdRoute
  '/customer/product/$id': typeof CustomerProductIdRoute
  '/delivery/task/$id': typeof DeliveryTaskIdRoute
  '/shopkeeper/orders/$id': typeof ShopkeeperOrdersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/customer': typeof CustomerRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/delivery': typeof DeliveryRouteWithChildren
  '/login': typeof LoginRoute
  '/products': typeof ProductsRoute
  '/shopkeeper': typeof ShopkeeperRouteWithChildren
  '/signup': typeof SignupRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/collections': typeof AdminCollectionsRoute
  '/admin/complaints': typeof AdminComplaintsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/delivery-partners': typeof AdminDeliveryPartnersRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shops': typeof AdminShopsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/customer/cart': typeof CustomerCartRoute
  '/customer/categories': typeof CustomerCategoriesRoute
  '/customer/checkout': typeof CustomerCheckoutRoute
  '/customer/home': typeof CustomerHomeRoute
  '/customer/notifications': typeof CustomerNotificationsRoute
  '/customer/orders': typeof CustomerOrdersRouteWithChildren
  '/customer/profile': typeof CustomerProfileRoute
  '/customer/shop': typeof CustomerShopRoute
  '/customer/wishlist': typeof CustomerWishlistRoute
  '/delivery/available-orders': typeof DeliveryAvailableOrdersRoute
  '/delivery/dashboard': typeof DeliveryDashboardRoute
  '/delivery/earnings': typeof DeliveryEarningsRoute
  '/delivery/history': typeof DeliveryHistoryRoute
  '/delivery/notifications': typeof DeliveryNotificationsRoute
  '/delivery/profile': typeof DeliveryProfileRoute
  '/orders/$id': typeof OrdersIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/shopkeeper/dashboard': typeof ShopkeeperDashboardRoute
  '/shopkeeper/earnings': typeof ShopkeeperEarningsRoute
  '/shopkeeper/notifications': typeof ShopkeeperNotificationsRoute
  '/shopkeeper/offers': typeof ShopkeeperOffersRoute
  '/shopkeeper/orders': typeof ShopkeeperOrdersRouteWithChildren
  '/shopkeeper/products': typeof ShopkeeperProductsRoute
  '/shopkeeper/reviews': typeof ShopkeeperReviewsRoute
  '/shopkeeper/settings': typeof ShopkeeperSettingsRoute
  '/orders/': typeof OrdersIndexRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/api/public/OneSignalSDKUpdaterWorker.js': typeof ApiPublicOneSignalSDKUpdaterWorkerDotjsRoute
  '/api/public/OneSignalSDKWorker.js': typeof ApiPublicOneSignalSDKWorkerDotjsRoute
  '/customer/orders/$id': typeof CustomerOrdersIdRoute
  '/customer/product/$id': typeof CustomerProductIdRoute
  '/delivery/task/$id': typeof DeliveryTaskIdRoute
  '/shopkeeper/orders/$id': typeof ShopkeeperOrdersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/app'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/customer'
    | '/dashboard'
    | '/delivery'
    | '/login'
    | '/products'
    | '/shopkeeper'
    | '/signup'
    | '/admin/categories'
    | '/admin/collections'
    | '/admin/complaints'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/delivery-partners'
    | '/admin/notifications'
    | '/admin/offers'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/shops'
    | '/category/$slug'
    | '/customer/cart'
    | '/customer/categories'
    | '/customer/checkout'
    | '/customer/home'
    | '/customer/notifications'
    | '/customer/orders'
    | '/customer/profile'
    | '/customer/shop'
    | '/customer/wishlist'
    | '/delivery/available-orders'
    | '/delivery/dashboard'
    | '/delivery/earnings'
    | '/delivery/history'
    | '/delivery/notifications'
    | '/delivery/profile'
    | '/orders/$id'
    | '/product/$slug'
    | '/shopkeeper/dashboard'
    | '/shopkeeper/earnings'
    | '/shopkeeper/notifications'
    | '/shopkeeper/offers'
    | '/shopkeeper/orders'
    | '/shopkeeper/products'
    | '/shopkeeper/reviews'
    | '/shopkeeper/settings'
    | '/orders/'
    | '/admin/orders/$id'
    | '/api/public/OneSignalSDKUpdaterWorker.js'
    | '/api/public/OneSignalSDKWorker.js'
    | '/customer/orders/$id'
    | '/customer/product/$id'
    | '/delivery/task/$id'
    | '/shopkeeper/orders/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/app'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/customer'
    | '/dashboard'
    | '/delivery'
    | '/login'
    | '/products'
    | '/shopkeeper'
    | '/signup'
    | '/admin/categories'
    | '/admin/collections'
    | '/admin/complaints'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/delivery-partners'
    | '/admin/notifications'
    | '/admin/offers'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/shops'
    | '/category/$slug'
    | '/customer/cart'
    | '/customer/categories'
    | '/customer/checkout'
    | '/customer/home'
    | '/customer/notifications'
    | '/customer/orders'
    | '/customer/profile'
    | '/customer/shop'
    | '/customer/wishlist'
    | '/delivery/available-orders'
    | '/delivery/dashboard'
    | '/delivery/earnings'
    | '/delivery/history'
    | '/delivery/notifications'
    | '/delivery/profile'
    | '/orders/$id'
    | '/product/$slug'
    | '/shopkeeper/dashboard'
    | '/shopkeeper/earnings'
    | '/shopkeeper/notifications'
    | '/shopkeeper/offers'
    | '/shopkeeper/orders'
    | '/shopkeeper/products'
    | '/shopkeeper/reviews'
    | '/shopkeeper/settings'
    | '/orders'
    | '/admin/orders/$id'
    | '/api/public/OneSignalSDKUpdaterWorker.js'
    | '/api/public/OneSignalSDKWorker.js'
    | '/customer/orders/$id'
    | '/customer/product/$id'
    | '/delivery/task/$id'
    | '/shopkeeper/orders/$id'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/app'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/customer'
    | '/dashboard'
    | '/delivery'
    | '/login'
    | '/products'
    | '/shopkeeper'
    | '/signup'
    | '/admin/categories'
    | '/admin/collections'
    | '/admin/complaints'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/delivery-partners'
    | '/admin/notifications'
    | '/admin/offers'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/shops'
    | '/category/$slug'
    | '/customer/cart'
    | '/customer/categories'
    | '/customer/checkout'
    | '/customer/home'
    | '/customer/notifications'
    | '/customer/orders'
    | '/customer/profile'
    | '/customer/shop'
    | '/customer/wishlist'
    | '/delivery/available-orders'
    | '/delivery/dashboard'
    | '/delivery/earnings'
    | '/delivery/history'
    | '/delivery/notifications'
    | '/delivery/profile'
    | '/orders/$id'
    | '/product/$slug'
    | '/shopkeeper/dashboard'
    | '/shopkeeper/earnings'
    | '/shopkeeper/notifications'
    | '/shopkeeper/offers'
    | '/shopkeeper/orders'
    | '/shopkeeper/products'
    | '/shopkeeper/reviews'
    | '/shopkeeper/settings'
    | '/orders/'
    | '/admin/orders/$id'
    | '/api/public/OneSignalSDKUpdaterWorker.js'
    | '/api/public/OneSignalSDKWorker.js'
    | '/customer/orders/$id'
    | '/customer/product/$id'
    | '/delivery/task/$id'
    | '/shopkeeper/orders/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRoute
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  CustomerRoute: typeof CustomerRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  DeliveryRoute: typeof DeliveryRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProductsRoute: typeof ProductsRoute
  ShopkeeperRoute: typeof ShopkeeperRouteWithChildren
  SignupRoute: typeof SignupRoute
  CategorySlugRoute: typeof CategorySlugRoute
  OrdersIdRoute: typeof OrdersIdRoute
  ProductSlugRoute: typeof ProductSlugRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  ApiPublicOneSignalSDKUpdaterWorkerDotjsRoute: typeof ApiPublicOneSignalSDKUpdaterWorkerDotjsRoute
  ApiPublicOneSignalSDKWorkerDotjsRoute: typeof ApiPublicOneSignalSDKWorkerDotjsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopkeeper': {
      id: '/shopkeeper'
      path: '/shopkeeper'
      fullPath: '/shopkeeper'
      preLoaderRoute: typeof ShopkeeperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer': {
      id: '/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopkeeper/settings': {
      id: '/shopkeeper/settings'
      path: '/settings'
      fullPath: '/shopkeeper/settings'
      preLoaderRoute: typeof ShopkeeperSettingsRouteImport
      parentRoute: typeof ShopkeeperRoute
    }
    '/shopkeeper/reviews': {
      id: '/shopkeeper/reviews'
      path: '/reviews'
      fullPath: '/shopkeeper/reviews'
      preLoaderRoute: typeof ShopkeeperReviewsRouteImport
      parentRoute: typeof ShopkeeperRoute
    }
    '/shopkeeper/products': {
      id: '/shopkeeper/products'
      path: '/products'
      fullPath: '/shopkeeper/products'
      preLoaderRoute: typeof ShopkeeperProductsRouteImport
      parentRoute: typeof ShopkeeperRoute
    }
    '/shopkeeper/orders': {
      id: '/shopkeeper/orders'
      path: '/orders'
      fullPath: '/shopkeeper/orders'
      preLoaderRoute: typeof ShopkeeperOrdersRouteImport
      parentRoute: typeof ShopkeeperRoute
    }
    '/shopkeeper/offers': {
      id: '/shopkeeper/offers'
      path: '/offers'
      fullPath: '/shopkeeper/offers'
      preLoaderRoute: typeof ShopkeeperOffersRouteImport
      parentRoute: typeof ShopkeeperRoute
    }
    '/shopkeeper/notifications': {
      id: '/shopkeeper/notifications'
      path: '/notifications'
      fullPath: '/shopkeeper/notifications'
      preLoaderRoute: typeof ShopkeeperNotificationsRouteImport
      parentRoute: typeof ShopkeeperRoute
    }
    '/shopkeeper/earnings': {
      id: '/shopkeeper/earnings'
      path: '/earnings'
      fullPath: '/shopkeeper/earnings'
      preLoaderRoute: typeof ShopkeeperEarningsRouteImport
      parentRoute: typeof ShopkeeperRoute
    }
    '/shopkeeper/dashboard': {
      id: '/shopkeeper/dashboard'
      path: '/dashboard'
      fullPath: '/shopkeeper/dashboard'
      preLoaderRoute: typeof ShopkeeperDashboardRouteImport
      parentRoute: typeof ShopkeeperRoute
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery/profile': {
      id: '/delivery/profile'
      path: '/profile'
      fullPath: '/delivery/profile'
      preLoaderRoute: typeof DeliveryProfileRouteImport
      parentRoute: typeof DeliveryRoute
    }
    '/delivery/notifications': {
      id: '/delivery/notifications'
      path: '/notifications'
      fullPath: '/delivery/notifications'
      preLoaderRoute: typeof DeliveryNotificationsRouteImport
      parentRoute: typeof DeliveryRoute
    }
    '/delivery/history': {
      id: '/delivery/history'
      path: '/history'
      fullPath: '/delivery/history'
      preLoaderRoute: typeof DeliveryHistoryRouteImport
      parentRoute: typeof DeliveryRoute
    }
    '/delivery/earnings': {
      id: '/delivery/earnings'
      path: '/earnings'
      fullPath: '/delivery/earnings'
      preLoaderRoute: typeof DeliveryEarningsRouteImport
      parentRoute: typeof DeliveryRoute
    }
    '/delivery/dashboard': {
      id: '/delivery/dashboard'
      path: '/dashboard'
      fullPath: '/delivery/dashboard'
      preLoaderRoute: typeof DeliveryDashboardRouteImport
      parentRoute: typeof DeliveryRoute
    }
    '/delivery/available-orders': {
      id: '/delivery/available-orders'
      path: '/available-orders'
      fullPath: '/delivery/available-orders'
      preLoaderRoute: typeof DeliveryAvailableOrdersRouteImport
      parentRoute: typeof DeliveryRoute
    }
    '/customer/wishlist': {
      id: '/customer/wishlist'
      path: '/wishlist'
      fullPath: '/customer/wishlist'
      preLoaderRoute: typeof CustomerWishlistRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/shop': {
      id: '/customer/shop'
      path: '/shop'
      fullPath: '/customer/shop'
      preLoaderRoute: typeof CustomerShopRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/profile': {
      id: '/customer/profile'
      path: '/profile'
      fullPath: '/customer/profile'
      preLoaderRoute: typeof CustomerProfileRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/orders': {
      id: '/customer/orders'
      path: '/orders'
      fullPath: '/customer/orders'
      preLoaderRoute: typeof CustomerOrdersRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/notifications': {
      id: '/customer/notifications'
      path: '/notifications'
      fullPath: '/customer/notifications'
      preLoaderRoute: typeof CustomerNotificationsRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/home': {
      id: '/customer/home'
      path: '/home'
      fullPath: '/customer/home'
      preLoaderRoute: typeof CustomerHomeRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/checkout': {
      id: '/customer/checkout'
      path: '/checkout'
      fullPath: '/customer/checkout'
      preLoaderRoute: typeof CustomerCheckoutRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/categories': {
      id: '/customer/categories'
      path: '/categories'
      fullPath: '/customer/categories'
      preLoaderRoute: typeof CustomerCategoriesRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/cart': {
      id: '/customer/cart'
      path: '/cart'
      fullPath: '/customer/cart'
      preLoaderRoute: typeof CustomerCartRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/shops': {
      id: '/admin/shops'
      path: '/shops'
      fullPath: '/admin/shops'
      preLoaderRoute: typeof AdminShopsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/offers': {
      id: '/admin/offers'
      path: '/offers'
      fullPath: '/admin/offers'
      preLoaderRoute: typeof AdminOffersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/delivery-partners': {
      id: '/admin/delivery-partners'
      path: '/delivery-partners'
      fullPath: '/admin/delivery-partners'
      preLoaderRoute: typeof AdminDeliveryPartnersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/complaints': {
      id: '/admin/complaints'
      path: '/complaints'
      fullPath: '/admin/complaints'
      preLoaderRoute: typeof AdminComplaintsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/collections': {
      id: '/admin/collections'
      path: '/collections'
      fullPath: '/admin/collections'
      preLoaderRoute: typeof AdminCollectionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/shopkeeper/orders/$id': {
      id: '/shopkeeper/orders/$id'
      path: '/$id'
      fullPath: '/shopkeeper/orders/$id'
      preLoaderRoute: typeof ShopkeeperOrdersIdRouteImport
      parentRoute: typeof ShopkeeperOrdersRoute
    }
    '/delivery/task/$id': {
      id: '/delivery/task/$id'
      path: '/task/$id'
      fullPath: '/delivery/task/$id'
      preLoaderRoute: typeof DeliveryTaskIdRouteImport
      parentRoute: typeof DeliveryRoute
    }
    '/customer/product/$id': {
      id: '/customer/product/$id'
      path: '/product/$id'
      fullPath: '/customer/product/$id'
      preLoaderRoute: typeof CustomerProductIdRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/orders/$id': {
      id: '/customer/orders/$id'
      path: '/$id'
      fullPath: '/customer/orders/$id'
      preLoaderRoute: typeof CustomerOrdersIdRouteImport
      parentRoute: typeof CustomerOrdersRoute
    }
    '/api/public/OneSignalSDKWorker.js': {
      id: '/api/public/OneSignalSDKWorker.js'
      path: '/api/public/OneSignalSDKWorker.js'
      fullPath: '/api/public/OneSignalSDKWorker.js'
      preLoaderRoute: typeof ApiPublicOneSignalSDKWorkerDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/OneSignalSDKUpdaterWorker.js': {
      id: '/api/public/OneSignalSDKUpdaterWorker.js'
      path: '/api/public/OneSignalSDKUpdaterWorker.js'
      fullPath: '/api/public/OneSignalSDKUpdaterWorker.js'
      preLoaderRoute: typeof ApiPublicOneSignalSDKUpdaterWorkerDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders/$id': {
      id: '/admin/orders/$id'
      path: '/$id'
      fullPath: '/admin/orders/$id'
      preLoaderRoute: typeof AdminOrdersIdRouteImport
      parentRoute: typeof AdminOrdersRoute
    }
  }
}

interface AdminOrdersRouteChildren {
  AdminOrdersIdRoute: typeof AdminOrdersIdRoute
}

const AdminOrdersRouteChildren: AdminOrdersRouteChildren = {
  AdminOrdersIdRoute: AdminOrdersIdRoute,
}

const AdminOrdersRouteWithChildren = AdminOrdersRoute._addFileChildren(
  AdminOrdersRouteChildren,
)

interface AdminRouteChildren {
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCollectionsRoute: typeof AdminCollectionsRoute
  AdminComplaintsRoute: typeof AdminComplaintsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDeliveryPartnersRoute: typeof AdminDeliveryPartnersRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminOffersRoute: typeof AdminOffersRoute
  AdminOrdersRoute: typeof AdminOrdersRouteWithChildren
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminShopsRoute: typeof AdminShopsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCollectionsRoute: AdminCollectionsRoute,
  AdminComplaintsRoute: AdminComplaintsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDeliveryPartnersRoute: AdminDeliveryPartnersRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminOffersRoute: AdminOffersRoute,
  AdminOrdersRoute: AdminOrdersRouteWithChildren,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminShopsRoute: AdminShopsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CustomerOrdersRouteChildren {
  CustomerOrdersIdRoute: typeof CustomerOrdersIdRoute
}

const CustomerOrdersRouteChildren: CustomerOrdersRouteChildren = {
  CustomerOrdersIdRoute: CustomerOrdersIdRoute,
}

const CustomerOrdersRouteWithChildren = CustomerOrdersRoute._addFileChildren(
  CustomerOrdersRouteChildren,
)

interface CustomerRouteChildren {
  CustomerCartRoute: typeof CustomerCartRoute
  CustomerCategoriesRoute: typeof CustomerCategoriesRoute
  CustomerCheckoutRoute: typeof CustomerCheckoutRoute
  CustomerHomeRoute: typeof CustomerHomeRoute
  CustomerNotificationsRoute: typeof CustomerNotificationsRoute
  CustomerOrdersRoute: typeof CustomerOrdersRouteWithChildren
  CustomerProfileRoute: typeof CustomerProfileRoute
  CustomerShopRoute: typeof CustomerShopRoute
  CustomerWishlistRoute: typeof CustomerWishlistRoute
  CustomerProductIdRoute: typeof CustomerProductIdRoute
}

const CustomerRouteChildren: CustomerRouteChildren = {
  CustomerCartRoute: CustomerCartRoute,
  CustomerCategoriesRoute: CustomerCategoriesRoute,
  CustomerCheckoutRoute: CustomerCheckoutRoute,
  CustomerHomeRoute: CustomerHomeRoute,
  CustomerNotificationsRoute: CustomerNotificationsRoute,
  CustomerOrdersRoute: CustomerOrdersRouteWithChildren,
  CustomerProfileRoute: CustomerProfileRoute,
  CustomerShopRoute: CustomerShopRoute,
  CustomerWishlistRoute: CustomerWishlistRoute,
  CustomerProductIdRoute: CustomerProductIdRoute,
}

const CustomerRouteWithChildren = CustomerRoute._addFileChildren(
  CustomerRouteChildren,
)

interface DeliveryRouteChildren {
  DeliveryAvailableOrdersRoute: typeof DeliveryAvailableOrdersRoute
  DeliveryDashboardRoute: typeof DeliveryDashboardRoute
  DeliveryEarningsRoute: typeof DeliveryEarningsRoute
  DeliveryHistoryRoute: typeof DeliveryHistoryRoute
  DeliveryNotificationsRoute: typeof DeliveryNotificationsRoute
  DeliveryProfileRoute: typeof DeliveryProfileRoute
  DeliveryTaskIdRoute: typeof DeliveryTaskIdRoute
}

const DeliveryRouteChildren: DeliveryRouteChildren = {
  DeliveryAvailableOrdersRoute: DeliveryAvailableOrdersRoute,
  DeliveryDashboardRoute: DeliveryDashboardRoute,
  DeliveryEarningsRoute: DeliveryEarningsRoute,
  DeliveryHistoryRoute: DeliveryHistoryRoute,
  DeliveryNotificationsRoute: DeliveryNotificationsRoute,
  DeliveryProfileRoute: DeliveryProfileRoute,
  DeliveryTaskIdRoute: DeliveryTaskIdRoute,
}

const DeliveryRouteWithChildren = DeliveryRoute._addFileChildren(
  DeliveryRouteChildren,
)

interface ShopkeeperOrdersRouteChildren {
  ShopkeeperOrdersIdRoute: typeof ShopkeeperOrdersIdRoute
}

const ShopkeeperOrdersRouteChildren: ShopkeeperOrdersRouteChildren = {
  ShopkeeperOrdersIdRoute: ShopkeeperOrdersIdRoute,
}

const ShopkeeperOrdersRouteWithChildren =
  ShopkeeperOrdersRoute._addFileChildren(ShopkeeperOrdersRouteChildren)

interface ShopkeeperRouteChildren {
  ShopkeeperDashboardRoute: typeof ShopkeeperDashboardRoute
  ShopkeeperEarningsRoute: typeof ShopkeeperEarningsRoute
  ShopkeeperNotificationsRoute: typeof ShopkeeperNotificationsRoute
  ShopkeeperOffersRoute: typeof ShopkeeperOffersRoute
  ShopkeeperOrdersRoute: typeof ShopkeeperOrdersRouteWithChildren
  ShopkeeperProductsRoute: typeof ShopkeeperProductsRoute
  ShopkeeperReviewsRoute: typeof ShopkeeperReviewsRoute
  ShopkeeperSettingsRoute: typeof ShopkeeperSettingsRoute
}

const ShopkeeperRouteChildren: ShopkeeperRouteChildren = {
  ShopkeeperDashboardRoute: ShopkeeperDashboardRoute,
  ShopkeeperEarningsRoute: ShopkeeperEarningsRoute,
  ShopkeeperNotificationsRoute: ShopkeeperNotificationsRoute,
  ShopkeeperOffersRoute: ShopkeeperOffersRoute,
  ShopkeeperOrdersRoute: ShopkeeperOrdersRouteWithChildren,
  ShopkeeperProductsRoute: ShopkeeperProductsRoute,
  ShopkeeperReviewsRoute: ShopkeeperReviewsRoute,
  ShopkeeperSettingsRoute: ShopkeeperSettingsRoute,
}

const ShopkeeperRouteWithChildren = ShopkeeperRoute._addFileChildren(
  ShopkeeperRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRoute,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  CustomerRoute: CustomerRouteWithChildren,
  DashboardRoute: DashboardRoute,
  DeliveryRoute: DeliveryRouteWithChildren,
  LoginRoute: LoginRoute,
  ProductsRoute: ProductsRoute,
  ShopkeeperRoute: ShopkeeperRouteWithChildren,
  SignupRoute: SignupRoute,
  CategorySlugRoute: CategorySlugRoute,
  OrdersIdRoute: OrdersIdRoute,
  ProductSlugRoute: ProductSlugRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  ApiPublicOneSignalSDKUpdaterWorkerDotjsRoute:
    ApiPublicOneSignalSDKUpdaterWorkerDotjsRoute,
  ApiPublicOneSignalSDKWorkerDotjsRoute: ApiPublicOneSignalSDKWorkerDotjsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
